import test from "node:test";
import assert from "node:assert/strict";
import { createProject } from "../src/model/schema.js";
import { projectHash, renderProjectSVG } from "../src/render/project-svg.js";

test("project export is byte deterministic and carries canonical metadata",()=>{const p=createProject({seed:"layered"});const a=renderProjectSVG(p);assert.equal(a,renderProjectSVG(p));assert.match(a,new RegExp(`data-lightwell-project="lw-${projectHash(p)}"`));assert.match(a,/<metadata>\{"schema":"lightwell.project"/);assert.match(a,/data-lightwell-layer="background"/);assert.match(a,/data-lightwell-layer="frame"/)});
test("project-scoped IDs do not collide across inline exports",()=>{const a=renderProjectSVG(createProject({seed:"one"})),b=renderProjectSVG(createProject({seed:"two"}));for(const generic of ['id="tile-0"','id="crackChaos"','url(#micaChaos)']){assert.ok(!a.includes(generic),generic);assert.ok(!b.includes(generic),generic)}const ids=s=>new Set([...s.matchAll(/ id="([^"]+)"/g)].map(m=>m[1]));const ai=ids(a),bi=ids(b);assert.equal([...ai].filter(x=>bi.has(x)).length,0)});
test("validated project export cannot inject SVG markup through colors",()=>{const p=createProject({crackColors:['\"/><script>alert(1)</script><x a="','#abcdef']});const svg=renderProjectSVG(p);assert.ok(!svg.includes('<script>'));assert.match(svg,/#35243a/)});

test("project export is well-formed XML by balanced structural groups",()=>{const svg=renderProjectSVG(createProject());assert.equal((svg.match(/<g\b/g)||[]).length,(svg.match(/<\/g>/g)||[]).length);assert.equal((svg.match(/<svg\b/g)||[]).length,1);assert.equal((svg.match(/<\/svg>/g)||[]).length,1)});
test("adversarial tile overrides cannot inject markup, attributes, or references",()=>{const p=createProject({tiles:{"0":{color:'\"/><script>alert(1)</script>',silhouette:'evil\"><image href="https://evil">',silhouetteColor:'url(javascript:alert(1))',opacity:'1 onload=alert(1)',scale:'NaN',positionX:'Infinity',positionY:'-999'}}});const svg=renderProjectSVG(p);for(const unsafe of ["<script","javascript:","onload=","https://evil"])assert.ok(!svg.includes(unsafe),unsafe);assert.match(svg,/fill="#9b70b4"/);assert.ok(!svg.includes('class="motif"'))});
test("renderer emits the complete stable semantic layer contract intentionally",()=>{const svg=renderProjectSVG(createProject({micaAmount:40,tiles:{"0":{silhouette:"leaf"}}}));const layers=[...svg.matchAll(/data-lightwell-layer="([^"]+)"/g)].map(x=>x[1]);assert.deepEqual(layers,["background","glass","mica","motifs","lead","lighting","frame"])});
test("optional instance namespaces avoid identical inline collisions without changing standalone determinism",()=>{const p=createProject({seed:"twins"}),standalone=renderProjectSVG(p),a=renderProjectSVG(p,{instanceNamespace:"left"}),b=renderProjectSVG(p,{instanceNamespace:"right"});assert.equal(standalone,renderProjectSVG(p));const ids=s=>new Set([...s.matchAll(/ id="([^"]+)"/g)].map(m=>m[1]));assert.equal([...ids(a)].filter(x=>ids(b).has(x)).length,0);assert.notEqual(a,b);assert.match(a,new RegExp(`data-lightwell-project="lw-${projectHash(p)}"`))});
