import test from "node:test";
import assert from "node:assert/strict";
import { createProject, normalizeProject, panelOptions, PROJECT_SCHEMA, PROJECT_VERSION, serializeProject } from "../src/model/schema.js";
import { createStore } from "../src/model/store.js";

test("project state has a versioned serializable geometry/material/tile model",()=>{const p=createProject();assert.equal(p.schema,PROJECT_SCHEMA);assert.equal(p.version,PROJECT_VERSION);assert.ok(p.geometry&&p.material&&p.defaults&&p.tiles);assert.deepEqual(normalizeProject(JSON.parse(serializeProject(p))),p)});
test("v0.1 controls map exactly to panel generator options",()=>{const p=createProject({seed:"glass",orientation:"landscape",pieceCount:5,hue:10,saturation:20,value:30,glassOpacity:40,leadWidth:7,leadStyle:"wavy",crackColors:["#112233","#445566"],crackOpacity:50,micaAmount:60,micaBrightness:70,micaDensity:20,micaColors:["#778899","#aabbcc"],micaOpacity:80});assert.deepEqual(panelOptions(p),{seed:"glass",cells:5,width:1200,height:760,hue:10,saturation:20,value:30,glassOpacity:40,lead:7,leadStyle:"wavy",crackColor1:"#112233",crackColor2:"#445566",crackOpacity:50,mica:60,micaBrightness:70,micaDensity:20,micaColor1:"#778899",micaColor2:"#aabbcc",micaOpacity:80})});
test("normalization rejects wrong versions and clamps unsafe values",()=>{assert.throws(()=>normalizeProject({schema:PROJECT_SCHEMA,version:999}),/Unsupported/);const p=createProject({pieceCount:999,leadStyle:"bogus",crackColors:["url(x)","#ABCDEF"]});assert.equal(p.geometry.pieceCount,70);assert.equal(p.material.lead.style,"ink");assert.deepEqual(p.material.lead.colors,["#35243a","#abcdef"])});
test("store snapshots cannot mutate current state and subscriptions can detach",()=>{const s=createStore(createProject()),seen=[];const off=s.subscribe(p=>seen.push(p.geometry.pieceCount));const snapshot=s.getState();snapshot.geometry.pieceCount=5;assert.equal(s.getState().geometry.pieceCount,32);s.update(p=>{p.geometry.pieceCount=12});off();s.update(p=>{p.geometry.pieceCount=14});assert.deepEqual(seen,[12]);assert.equal(s.getState().geometry.pieceCount,14)});
