import test from "node:test";
import assert from "node:assert/strict";
import { createProject } from "../src/model/schema.js";
import { projectHash, renderProjectSVG } from "../src/render/project-svg.js";
import { readFile } from "node:fs/promises";
const fileFetcher=async url=>({ok:true,arrayBuffer:async()=>{const b=await readFile(new URL(url));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}});

test("project export is byte deterministic and carries canonical metadata",async()=>{const p=createProject({seed:"layered"});const a=await renderProjectSVG(p);assert.equal(a,await renderProjectSVG(p));assert.match(a,new RegExp(`data-lightwell-project="lw-${projectHash(p)}"`));assert.match(a,/<metadata>\{"schema":"lightwell.project"/);assert.match(a,/data-lightwell-layer="background"/);assert.match(a,/data-lightwell-layer="frame"/)});
test("project-scoped IDs do not collide across inline exports",async()=>{const a=await renderProjectSVG(createProject({seed:"one"})),b=await renderProjectSVG(createProject({seed:"two"}));for(const generic of ['id="tile-0"','id="crackChaos"','url(#micaChaos)']){assert.ok(!a.includes(generic),generic);assert.ok(!b.includes(generic),generic)}const ids=s=>new Set([...s.matchAll(/ id="([^"]+)"/g)].map(m=>m[1]));const ai=ids(a),bi=ids(b);assert.equal([...ai].filter(x=>bi.has(x)).length,0)});
test("validated project export cannot inject SVG markup through colors",async()=>{const p=createProject({crackColors:['\"/><script>alert(1)</script><x a="','#abcdef']});const svg=await renderProjectSVG(p);assert.ok(!svg.includes('<script>'));assert.match(svg,/#35243a/)});

test("project export is well-formed XML by balanced structural groups",async()=>{const svg=await renderProjectSVG(createProject());assert.equal((svg.match(/<g\b/g)||[]).length,(svg.match(/<\/g>/g)||[]).length);assert.equal((svg.match(/<svg\b/g)||[]).length,1);assert.equal((svg.match(/<\/svg>/g)||[]).length,1)});
test("adversarial tile overrides cannot inject markup, attributes, or references",async()=>{const p=createProject({tiles:{"0":{color:'\"/><script>alert(1)</script>',silhouette:'evil\"><image href="https://evil">',silhouetteColor:'url(javascript:alert(1))',opacity:'1 onload=alert(1)',scale:'NaN',positionX:'Infinity',positionY:'-999'}}});const svg=await renderProjectSVG(p);for(const unsafe of ["<script","javascript:","onload=","https://evil"])assert.ok(!svg.includes(unsafe),unsafe);assert.match(svg,/fill="#9b70b4"/);assert.ok(!svg.includes('class="motif"'))});
test("renderer emits the complete stable semantic layer contract intentionally",async()=>{const svg=await renderProjectSVG(createProject({micaAmount:40,tiles:{"0":{silhouette:"leaf"}}}),{fetcher:fileFetcher});const layers=[...svg.matchAll(/data-lightwell-layer="([^"]+)"/g)].map(x=>x[1]);assert.deepEqual(layers,["background","glass","mica","motifs","lead","lighting","text","frame"])});
test("optional instance namespaces avoid identical inline collisions without changing standalone determinism",async()=>{const p=createProject({seed:"twins"}),standalone=await renderProjectSVG(p),a=await renderProjectSVG(p,{instanceNamespace:"left"}),b=await renderProjectSVG(p,{instanceNamespace:"right"});assert.equal(standalone,await renderProjectSVG(p));const ids=s=>new Set([...s.matchAll(/ id="([^"]+)"/g)].map(m=>m[1]));assert.equal([...ids(a)].filter(x=>ids(b).has(x)).length,0);assert.notEqual(a,b);assert.match(a,new RegExp(`data-lightwell-project="lw-${projectHash(p)}"`))});
test("library identity changes project hash and rendered art",async()=>{const base=createProject({seed:"library-contract",tiles:{"0":{silhouette:"leaf"}}}),legacy={...base,motifLibrary:"legacy-vector-v1"};assert.notEqual(projectHash(base),projectHash(legacy));const charcoal=await renderProjectSVG(base,{fetcher:fileFetcher}),vector=await renderProjectSVG(legacy,{fetcher:()=>{throw Error("legacy must not fetch PNGs")}});assert.match(charcoal,/data:image\/png;base64/);assert.doesNotMatch(vector,/data:image\/png;base64/);assert.notEqual(charcoal,vector)});
test("export embeds only used charcoal assets",async()=>{(await import("../src/catalog/charcoal-motifs.js")).clearCharcoalCache();let fetched=[];const fetcher=async url=>{fetched.push(url);return fileFetcher(url)};const svg=await renderProjectSVG(createProject({tiles:{"0":{silhouette:"leaf"},"1":{silhouette:"leaf"},"2":{silhouette:"moon"}}}),{fetcher});assert.equal(fetched.length,2);assert.equal((svg.match(/data:image\/png;base64/g)||[]).length,2);assert.ok(fetched.some(x=>x.endsWith("leaf.png")));assert.ok(fetched.some(x=>x.endsWith("moon.png")))});
test("failed charcoal export is explicit and never substitutes vectors",async()=>{(await import("../src/catalog/charcoal-motifs.js")).clearCharcoalCache();const p=createProject({tiles:{"0":{silhouette:"leaf"}}});await assert.rejects(()=>renderProjectSVG(p,{fetcher:async()=>({ok:false})}),/Unable to load motif asset: leaf/)});
test("text and deterministic motion export into self-contained SVG",async()=>{const p=createProject({seed:"moving-words",text:{content:"Glass & <glow>",color:"#abcdef",opacity:82,size:88,x:25,y:70,rotation:-12,font:"sans-serif",align:"start",clip:true},motion:{enabled:true,amount:10,duration:7}}),a=await renderProjectSVG(p),b=await renderProjectSVG(p);assert.equal(a,b);assert.match(a,/data-lightwell-layer="text"/);assert.match(a,/Glass &amp; &lt;glow&gt;/);assert.match(a,/font-family="sans-serif"/);assert.match(a,/rotate\(-12 /);assert.match(a,/<animateTransform[^>]+dur="7s"[^>]+repeatCount="indefinite"/);assert.ok(!a.includes("<glow>"))});
test("motion-disabled export contains no animation elements",async()=>assert.doesNotMatch(await renderProjectSVG(createProject({motion:{enabled:false}})),/<animateTransform/));
