export function hsvToHex(h,s,v){h=((Number(h)%360)+360)%360;s=Math.max(0,Math.min(100,Number(s)))/100;v=Math.max(0,Math.min(100,Number(v)))/100;const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let a=[0,0,0];if(h<60)a=[c,x,0];else if(h<120)a=[x,c,0];else if(h<180)a=[0,c,x];else if(h<240)a=[0,x,c];else if(h<300)a=[x,0,c];else a=[c,0,x];return"#"+a.map(n=>Math.round((n+m)*255).toString(16).padStart(2,"0")).join("")}
export function colorFamily(hue,saturation,value,count=7){const offsets=[0,28,-32,58,-66,110,180];return Array.from({length:count},(_,i)=>hsvToHex(hue+offsets[i%offsets.length],Math.max(12,saturation-(i%3)*10),Math.min(100,value+(i%2)*7)))}
export function hashSeed(seed){let h=2166136261;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function rng(seed){let a=hashSeed(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function clip(poly,a,b,c){const out=[];for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],dp=a*p.x+b*p.y-c,dq=a*q.x+b*q.y-c,inside=dp<=1e-7,next=dq<=1e-7;if(inside)out.push(p);if(inside!==next){const t=dp/(dp-dq);out.push({x:p.x+t*(q.x-p.x),y:p.y+t*(q.y-p.y)})}}return out}
function cell(p,others,x0,x1,y0,y1){let poly=[{x:x0,y:y0},{x:x1,y:y0},{x:x1,y:y1},{x:x0,y:y1}];for(const q of others){poly=clip(poly,2*(q.x-p.x),2*(q.y-p.y),q.x*q.x+q.y*q.y-p.x*p.x-p.y*p.y);if(!poly.length)break}return poly}
export function makePanel({seed="aventurine",width=900,height=1100,cells=32,hue=282,saturation=38,value=84,lead=9}={}){const r=rng(seed),colors=colorFamily(hue,saturation,value),m=Math.min(width,height)*.06,pts=[];for(let i=0;i<cells;i++)pts.push({x:m+r()*(width-2*m),y:m+r()*(height-2*m),c:colors[Math.floor(r()*colors.length)]});pts.push({x:m,y:m,c:colors[0]},{x:width-m,y:m,c:colors[1]},{x:width-m,y:height-m,c:colors[2]},{x:m,y:height-m,c:colors[3]});return{seed,width,height,hue,saturation,value,lead,polygons:pts.map((p,i)=>({id:i,fill:p.c,points:cell(p,pts.filter((_,j)=>j!==i),m,width-m,m,height-m)})).filter(x=>x.points.length>2)}}
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const pts=x=>x.points.map(q=>`${q.x.toFixed(2)},${q.y.toFixed(2)}`).join(" ");
function motif(kind,color,opacity){if(kind==="leaf")return`<path d="M450 770C250 650 230 350 470 250c170 170 110 390-20 520zm-5-45V330" fill="${color}" stroke="${color}" stroke-width="28" opacity="${opacity}"/>`;if(kind==="moon")return`<path d="M580 235c-230 70-260 420-24 522-350 34-477-424-186-598 68-40 142-52 210-42-2 40-2 78 0 118z" fill="${color}" opacity="${opacity}"/>`;if(kind==="spark")return`<path d="M450 180l62 245 238 72-238 72-62 245-62-245-238-72 238-72z" fill="${color}" opacity="${opacity}"/>`;return""}
export function panelToSVG(p,tileStyles={}){const clips=p.polygons.map(x=>`<clipPath id="tile-${x.id}"><polygon points="${pts(x)}"/></clipPath>`).join("");const tiles=p.polygons.map((x,i)=>{const style=tileStyles[x.id]||{},fill=style.color||x.fill,mark=motif(style.silhouette,style.silhouetteColor||"#171019",style.opacity??.72);return`<g class="tile" data-tile="${x.id}" tabindex="0" aria-label="Glass tile ${i+1}"><polygon points="${pts(x)}" fill="${fill}" opacity="${(.82+(i%4)*.04).toFixed(2)}"/>${mark?`<g clip-path="url(#tile-${x.id})">${mark}</g>`:""}</g>`}).join("");return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${p.width} ${p.height}" role="img" aria-label="Seeded stained-glass panel ${esc(p.seed)}"><defs>${clips}<filter id="g"><feGaussianBlur stdDeviation="18"/></filter><linearGradient id="w" y2="1"><stop stop-color="#fff" stop-opacity=".42"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient></defs><rect width="100%" height="100%" rx="18" fill="#2b202d"/><ellipse cx="48%" cy="36%" rx="36%" ry="32%" fill="#fff4df" opacity=".25" filter="url(#g)"/><g stroke="#35243a" stroke-width="${p.lead}" stroke-linejoin="round">${tiles}</g><rect x="${p.lead/2}" y="${p.lead/2}" width="${p.width-p.lead}" height="${p.height-p.lead}" rx="14" fill="url(#w)" pointer-events="none" stroke="#35243a" stroke-width="${p.lead}"/></svg>`}
